### ISSUE TITLE
http:CharsetToEncode

### ISSUE THREAD

**Issue by ghost** [lee8oi/durby#1]
Default install errors when grabbing a link from a channel.  Output is: Tcl error [weburlwatch]: invalid command name "http::CharsetToEncoding"

**Comment by ghost** [comment]
on line 1131

proc CharsetToEncoding {charset} {

should read

proc http::CharsetToEncoding {charset} {

**Comment by lee8oi** [comment]
Encoding issues should now be fixed. Hopefully after updating to the latest copy of durby you should no longer experience this issue. Please create new issue if further problems arise. thanks.
