### ISSUE TITLE
Feature Request: Ignore nicks

### ISSUE THREAD

**Issue by w0ng** [lee8oi/durby#2]
(Firstly, thanks for this script. Secondly, I don't know any tcl so this may sound dumb)

What would be the best way to ignore url pattern matches from a specified nick -> if ($nick == "abc") {return 0}?

e.g. in a channel there are other bots that do google searches, another for youtube, etc and so I'd like to ignore links posted by them.

**Comment by lee8oi** [comment]
Certainly a great idea. I haven't been working on my eggdrop scripts 
lately but I'm hoping to get an update for durby posted sooner or later. 
But I'll definitely work this idea in. Certainly makes sense.

**Comment by lee8oi** [comment]
Ok this feature has been added to the latest version 0.2.8. Enjoy!

**Comment by w0ng** [comment]
Thanks! Working great
